/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shadermetal_proxy_WindowProxy */

#ifndef _Included_com_example_shadermetal_proxy_WindowProxy
#define _Included_com_example_shadermetal_proxy_WindowProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shadermetal_proxy_WindowProxy
 * Method:    onFramebufferSizeChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_WindowProxy_onFramebufferSizeChanged
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
