/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shadermetal_proxy_DrawCommandProxy */

#ifndef _Included_com_example_shadermetal_proxy_DrawCommandProxy
#define _Included_com_example_shadermetal_proxy_DrawCommandProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shadermetal_proxy_DrawCommandProxy
 * Method:    draw
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_DrawCommandProxy_draw
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
