/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shadermetal_proxy_ShaderProxy */

#ifndef _Included_com_example_shadermetal_proxy_ShaderProxy
#define _Included_com_example_shadermetal_proxy_ShaderProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shadermetal_proxy_ShaderProxy
 * Method:    registerShader
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_example_shadermetal_proxy_ShaderProxy_registerShader
  (JNIEnv *, jclass, jstring, jint, jstring, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
