/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shadermetal_proxy_PipelineStateProxy */

#ifndef _Included_com_example_shadermetal_proxy_PipelineStateProxy
#define _Included_com_example_shadermetal_proxy_PipelineStateProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    setScissorEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_setScissorEnabled
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    setScissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_setScissor
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    setViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_setViewport
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    setBlendEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_setBlendEnable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    setColorBlendConstants
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_setColorBlendConstants
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    setColorLogicOpEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_setColorLogicOpEnable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetBlendFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetBlendFuncSeparate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetBlendOpSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetBlendOpSeparate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetColorWriteMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetColorWriteMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetColorLogicOp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetColorLogicOp
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    setDepthTestEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_setDepthTestEnable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    setDepthWriteEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_setDepthWriteEnable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    setStencilTestEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_setStencilTestEnable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetDepthCompareOp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetDepthCompareOp
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetStencilFrontFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetStencilFrontFunc
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetStencilBackFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetStencilBackFunc
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetStencilFrontOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetStencilFrontOp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetStencilBackOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetStencilBackOp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetStencilFrontWriteMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetStencilFrontWriteMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetStencilBackWriteMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetStencilBackWriteMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    setLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_setLineWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetPolygonMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetPolygonMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetCullMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetCullMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetFrontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetFrontFace
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetDepthBiasEnable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetDepthBiasEnable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_PipelineStateProxy
 * Method:    vkSetDepthBias
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_PipelineStateProxy_vkSetDepthBias
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
