/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shadermetal_proxy_ChunkProxy */

#ifndef _Included_com_example_shadermetal_proxy_ChunkProxy
#define _Included_com_example_shadermetal_proxy_ChunkProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shadermetal_proxy_ChunkProxy
 * Method:    initNative
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_ChunkProxy_initNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_ChunkProxy
 * Method:    updateSectionPosNative
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_ChunkProxy_updateSectionPosNative
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_ChunkProxy
 * Method:    build
 * Signature: (IIIJIJJJJJJZ)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_ChunkProxy_build
  (JNIEnv *, jclass, jint, jint, jint, jlong, jint, jlong, jlong, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_ChunkProxy
 * Method:    isChunkReady
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_shadermetal_proxy_ChunkProxy_isChunkReady
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_shadermetal_proxy_ChunkProxy
 * Method:    relocateSingle
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_ChunkProxy_relocateSingle
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_ChunkProxy
 * Method:    invalidateSingle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_ChunkProxy_invalidateSingle
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
