/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shadermetal_proxy_RendererProxy */

#ifndef _Included_com_example_shadermetal_proxy_RendererProxy
#define _Included_com_example_shadermetal_proxy_RendererProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    initFolderPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_initFolderPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    initRenderer
 * Signature: ([Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_initRenderer
  (JNIEnv *, jclass, jobjectArray, jlong);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    setVsync
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_setVsync
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    maxSupportedTextureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_shadermetal_proxy_RendererProxy_maxSupportedTextureSize
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    acquireContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_acquireContext
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    submitCommand
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_submitCommand
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    present
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_present
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    fuseWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_fuseWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    postBlur
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_postBlur
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_close
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    resetRayTracingScene
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_resetRayTracingScene
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    shouldRenderWorld
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_shouldRenderWorld
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    takeScreenshot
 * Signature: (ZIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_takeScreenshot
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jlong);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    updateWorldUniform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_updateWorldUniform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    updateSkyUniform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_updateSkyUniform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    updateOverlayPostUniform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_updateOverlayPostUniform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    setCameraPos
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_setCameraPos
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    setCameraSubmergedInWater
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_setCameraSubmergedInWater
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    setLocalPlayerShadowProxy
 * Signature: (ZFFFFIFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_setLocalPlayerShadowProxy
  (JNIEnv *, jclass, jboolean, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    setCelestialLighting
 * Signature: (FFFFFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_setCelestialLighting
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    setLocalLights
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_setLocalLights
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    setClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_setClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    setClearDepth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_setClearDepth
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    setClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_setClearStencil
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    vkCmdClearEntireColorAttachment
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_vkCmdClearEntireColorAttachment
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_RendererProxy
 * Method:    vkCmdClearEntireDepthStencilAttachment
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_RendererProxy_vkCmdClearEntireDepthStencilAttachment
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
