/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shadermetal_proxy_BufferProxy */

#ifndef _Included_com_example_shadermetal_proxy_BufferProxy
#define _Included_com_example_shadermetal_proxy_BufferProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shadermetal_proxy_BufferProxy
 * Method:    allocateBuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_shadermetal_proxy_BufferProxy_allocateBuffer
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_BufferProxy
 * Method:    initializeBuffer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_BufferProxy_initializeBuffer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_BufferProxy
 * Method:    queueUpload
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_BufferProxy_queueUpload
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_example_shadermetal_proxy_BufferProxy
 * Method:    performQueuedUpload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_BufferProxy_performQueuedUpload
  (JNIEnv *, jclass);

/*
 * Class:     com_example_shadermetal_proxy_BufferProxy
 * Method:    buildIndexBuffer
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_BufferProxy_buildIndexBuffer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_example_shadermetal_proxy_BufferProxy
 * Method:    updateMapping
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_shadermetal_proxy_BufferProxy_updateMapping
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
